// tslint:disable:no-magic-numbers

import { Frequency, Index, Power, to } from '@musical-patterns/utilities'

const XENHARMONIC_SERIES_INITIAL_LOWER_BOUND: Index = to.Index(1)
const XENHARMONIC_SERIES_INITIAL_UPPER_BOUND: Index = to.Index(32)

const XENHARMONIC_SERIES_INITIAL_BASE_FREQUENCY: Frequency = to.Frequency(220)
const XENHARMONIC_SERIES_INITIAL_POWER: Power = to.Power(-1)

export {
    XENHARMONIC_SERIES_INITIAL_LOWER_BOUND,
    XENHARMONIC_SERIES_INITIAL_UPPER_BOUND,
    XENHARMONIC_SERIES_INITIAL_BASE_FREQUENCY,
    XENHARMONIC_SERIES_INITIAL_POWER,
}
